# Generated by Django 5.1.4 on 2025-12-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
