# Generated by Django 5.1.4 on 2026-01-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_faq_bottlereturn_notification_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='preuve_validee',
            field=models.BooleanField(default=False),
        ),
    ]
