# Generated by Django 5.1.4 on 2026-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_livraison_preuve_validee'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='statut_livraison',
            field=models.CharField(choices=[('assigned', 'Assignée'), ('en_route', 'En route'), ('arriving', 'Arrive bientôt'), ('delivered', 'Livrée')], default='assigned', help_text='Statut de progression de la livraison', max_length=20),
        ),
    ]
