# Generated by Django 5.2.8 on 2026-01-28 15:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delivery_latitude',
            field=models.FloatField(blank=True, help_text='Latitude du lieu de livraison souhaité', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_longitude',
            field=models.FloatField(blank=True, help_text='Longitude du lieu de livraison souhaité', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_souhaitee',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date souhaitée pour la livraison'),
        ),
    ]
