services:
  - type: web
    name: essivi-backend
    runtime: docker
    dockerfilePath: ./infrastructure/docker/Dockerfile
    healthCheckPath: /health/
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: essivi-backend.onrender.com
      # Database (Supabase)
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres.jnctexyelciszovwurxn
      - key: POSTGRES_PASSWORD
        value: essivivi2026
      - key: POSTGRES_HOST
        value: aws-1-eu-west-3.pooler.supabase.com
      - key: POSTGRES_PORT
        value: 5432
      # MongoDB Atlas
      - key: MONGO_URI
        value: mongodb+srv://armel:essivivi2026@cluster0.tbovg5b.mongodb.net/?appName=Cluster0
      - key: MONGO_DB_NAME
        value: essivi_analytics
      # Redis Cloud
      - key: REDIS_HOST
        value: redis-16087.crce202.eu-west-3-1.ec2.cloud.redislabs.com
      - key: REDIS_PORT
        value: 16087
      - key: REDIS_USERNAME
        value: default
      - key: REDIS_PASSWORD
        value: ZhTieGsmKADyHge0M17mPxbVIcOGTxZG
      - key: REDIS_DB
        value: 0
      - key: REDIS_DECODE_RESPONSES
        value: true
      # Appwrite
      - key: APPWRITE_ENDPOINT
        value: https://cloud.appwrite.io/v1
      - key: APPWRITE_PROJECT_ID
        value: 697487ca003040b21700
      - key: APPWRITE_API_KEY
        value: standard_606a41923ff9ff9de1608429667e895cf0de95e87fd4000d125c095abc998ddddf11562afa0e72d2a686501ea9f94640b974117e6110cca9067df7ce6d3c6f7525d47b5d6a90404d869ef4ffaaa9123ddeed7e317fadffb7d41d12c05406bb684cf95b17b60c847b036a44cddc1385ab958ab38e589162e79e39f4aecf01a5bf
      # CORS
      - key: CORS_ALLOWED_ORIGINS
        value: https://essivivi.vercel.app,https://essivi-mobile.onrender.com