# Generated by Django 6.0 on 2025-12-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('stock_initial', models.IntegerField(default=0)),
                ('stock_retour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En Maintenance'), ('inactive', 'Inactif')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
