# Generated by Django 5.1.4 on 2026-01-10 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('users', '0006_agentprofile_current_speed_agentprofile_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Précision en mètres', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Vitesse en km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction en degrés', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='users.agentprofile')),
            ],
            options={
                'verbose_name': 'Historique de position',
                'verbose_name_plural': 'Historiques de positions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', '-timestamp'], name='logistics_l_agent_i_468101_idx')],
            },
        ),
    ]
