# Generated by Django 5.1.4 on 2025-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agentprofile_latitude_agentprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='nom_proprietaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
