# Generated by Django 5.1.4 on 2025-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprofile_adresse_clientprofile_nom_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='tricycle_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
