# Generated by Django 5.1.4 on 2026-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='current_speed',
            field=models.FloatField(blank=True, help_text='Vitesse en km/h', null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction en degrés (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
