# Generated by Django 5.1.4 on 2026-01-23 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agentprofile_current_speed_agentprofile_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude entre -90 et 90', null=True, validators=[django.core.validators.MinValueValidator(-90.0, message='Latitude must be >= -90'), django.core.validators.MaxValueValidator(90.0, message='Latitude must be <= 90')]),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude entre -180 et 180', null=True, validators=[django.core.validators.MinValueValidator(-180.0, message='Longitude must be >= -180'), django.core.validators.MaxValueValidator(180.0, message='Longitude must be <= 180')]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Solde cannot be negative')]),
        ),
    ]
