# Generated by Django 5.2.8 on 2026-01-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_agentprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='nom_point_vente',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
