# Generated by Django 5.2.8 on 2026-01-27 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Solde cannot be negative')]),
        ),
    ]
