# Generated by Django 5.2.8 on 2026-01-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_agentprofile_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Device FCM token for push notifications', max_length=255, null=True),
        ),
    ]
